[package]
name = "AthletePerformanceTracker"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
axum = "0.8.1"
serde_json = "1.0.140"
serde = { version = "1.0.218", features = ["derive"] }
